services:
  - type: web
    name: jamcraft-backend
    runtime: node
    buildCommand: npm install && pip3 install yt-dlp
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
